import { ArrowRight, Eye, Megaphone, MapPin, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useListFeaturedAdvertisements } from "@workspace/api-client-react";

function SponsoredBadge() { return <span className="inline-flex items-center gap-1 rounded-full bg-[#f5b916] px-2 py-1 text-[9px] font-black text-[#0e2f62]"><Sparkles className="h-3 w-3" />إعلان ممول</span>; }

export default function SponsoredPreview() {
  const { data: ads = [], isLoading } = useListFeaturedAdvertisements();
  const previewAds = ads.slice(0, 6);
  return <main className="min-h-[100dvh] bg-[#f7f8fa] pb-24 text-[#0e2f62]" dir="rtl"><header className="sticky top-0 z-10 border-b border-[#0e2f62]/[0.06] bg-white/95 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-lg items-center gap-3"><Link href="/" className="flex h-10 w-10 items-center justify-center rounded-full border border-[#dfe5ec] bg-white"><ArrowRight className="h-4 w-4" /></Link><div><p className="text-[11px] font-bold text-[#708198]">معاينة داخل تطبيق العميل</p><h1 className="text-xl font-black">الإعلانات الممولة</h1></div></div></header><div className="mx-auto max-w-lg space-y-6 px-4 pt-5"><section className="rounded-[24px] bg-[#0e2f62] p-5 text-white shadow-[0_12px_28px_rgba(14,47,98,0.16)]"><div className="flex items-start gap-3"><div className="rounded-2xl bg-[#f5b916] p-3 text-[#0e2f62]"><Megaphone className="h-6 w-6" /></div><div><h2 className="text-lg font-black">كيف يظهر الإعلان للعميل؟</h2><p className="mt-1 text-xs leading-5 text-white/70">هذه الصفحة تعرض نماذج الظهور الفعلية مع شارة واضحة تميّز الإعلان عن النتائج العادية.</p></div></div></section><section><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-[#f5b916]/15 px-2 py-1 text-[10px] font-bold text-[#8c6b00]">الصفحة الرئيسية</span><h2 className="text-[15px] font-black">مهنيون مميزون</h2></div><div className="space-y-3">{isLoading ? <div className="rounded-2xl bg-white p-6 text-center text-xs text-[#708198]">جاري تحميل الإعلانات...</div> : previewAds.length === 0 ? <div className="rounded-2xl border border-dashed border-[#cbd5e1] bg-white p-6 text-center text-xs text-[#708198]">لا توجد إعلانات نشطة حاليًا.</div> : previewAds.slice(0, 2).map((ad) => <AdCard key={`home-${ad.id}`} ad={ad} large />)}</div></section><section><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-[#eef2f6] px-2 py-1 text-[10px] font-bold text-[#60728a]">نتائج البحث</span><h2 className="text-[15px] font-black">إعلان بين النتائج</h2></div><div className="space-y-2">{previewAds.slice(0, 3).map((ad) => <AdRow key={`search-${ad.id}`} ad={ad} />)}</div></section><section><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-[#eef2f6] px-2 py-1 text-[10px] font-bold text-[#60728a]">صفحة التخصص</span><h2 className="text-[15px] font-black">ظهور داخل القسم</h2></div><div className="rounded-[20px] border border-[#eadba7] bg-[#fffdf4] p-4 shadow-[0_5px_14px_rgba(14,47,98,0.05)]">{previewAds[0] ? <AdCard ad={previewAds[0]} /> : <p className="text-center text-xs text-[#708198]">ستظهر المعاينة عند اعتماد أول إعلان.</p>}</div></section><div className="flex items-center gap-2 rounded-2xl border border-[#dce7f5] bg-[#eef5ff] p-4 text-xs leading-5 text-[#315a86]"><Eye className="h-4 w-4 shrink-0" />تظهر الإعلانات فقط بعد اعتمادها وتبقى شارة «إعلان ممول» واضحة للعميل.</div></div></main>;
}

function AdCard({ ad, large = false }: { ad: any; large?: boolean }) { return <Link href={`/providers/${ad.providerId}`}><article className={`rounded-[18px] border border-[#eadba7] bg-[#fffdf4] p-4 shadow-[0_5px_14px_rgba(14,47,98,0.05)] ${large ? "min-h-[118px]" : ""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black">{ad.title}</p><p className="mt-1 flex items-center gap-1 truncate text-[11px] text-[#708198]"><span>{ad.providerName || "مهني موصى به"}</span>{ad.city && <><span>·</span><MapPin className="h-3 w-3" />{ad.city}</>}</p></div><SponsoredBadge /></div>{ad.description && <p className="mt-3 line-clamp-2 text-[11px] leading-5 text-[#60728a]">{ad.description}</p>}</article></Link>; }
function AdRow({ ad }: { ad: any }) { return <Link href={`/providers/${ad.providerId}`}><article className="flex items-center gap-3 rounded-[17px] border border-[#e5e9ee] bg-white p-3 shadow-[0_4px_12px_rgba(14,47,98,0.04)]"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#fff5db] text-[#8c6b00]"><Megaphone className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{ad.title}</p><p className="mt-1 truncate text-[11px] text-[#708198]">{ad.providerName || "مهني موصى به"} · {ad.categoryName || "خدمات متنوعة"}</p></div><SponsoredBadge /></article></Link>; }
